name: Automatically merge pull requests
on:
  workflow_call:
    inputs:
      pr:
        required: true
        type: string
jobs:
  merge:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Merge the pull request
        run: |
          gh pr merge --auto --delete-branch --squash -- "${PR}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ inputs.pr }}
